spring:
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/gateway/**
          filters:
            - RewritePath=/baeldung/gateway/(?<RID>.*), /spring-cloud-gateway/$\{RID}
management:
  endpoints:
    web:
      exposure:
        include: "*"